spring:
      datasource:
                url: jdbc:postgresql://dpg-cpqgfd5ds78s73chmtv0-a.oregon-postgres.render.com:5432/cinepopdb2_tdg8
                username: daniel98el
                password: oLuOjB9EJTDgHHaIgbrQTATPm3R5vffx

#                url: jdbc:postgresql://localhost:5432/cinePop
#                username: postgres
#                password: whatisbeyond
                driver-class-name: org.postgresql.Driver
      jpa:
          database-platform: org.hibernate.dialect.PostgreSQLDialect
      data:
        web:
          pageable:
            one-indexed-parameters: true
      jackson:
        time-zone: UTC
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
logging:
        level:
              org:
                  hibernate:
                            SQL: DEBUG