spring:
      datasource:
                url: postgres://knightel98:FqikQEsWq6uyNoI5JCL5lieKQ9jXHDYA@dpg-cmjq8rfqd2ns73bkjh1g-a.frankfurt-postgres.render.com/cinepop_db
                username: knightel98
                password: FqikQEsWq6uyNoI5JCL5lieKQ9jXHDYA
                driver-class-name: org.postgresql.Driver
      jpa:
          database-platform: org.hibernate.dialect.PostgreSQLDialect
      data:
        web:
          pageable:
            one-indexed-parameters: true
      jackson:
        time-zone: UTC
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
logging:
        level:
              org:
                  hibernate:
                            SQL: DEBUG

