spring:
      datasource:
                url: jdbc:postgresql://aws-0-sa-east-1.pooler.supabase.com:6543/postgres?user=postgres.hhesurrrvjshwknsgckr&password=EsTaEsMiContra123
                username: postgres.hhesurrrvjshwknsgckr
                password: EsTaEsMiContra123

#                url: jdbc:postgresql://localhost:5432/cinePop
#                username: postgres
#                password: whatisbeyond

                driver-class-name: org.postgresql.Driver
      jpa:
          database-platform: org.hibernate.dialect.PostgreSQLDialect
      data:
        web:
          pageable:
            one-indexed-parameters: true
      jackson:
        time-zone: UTC
        date-format: yyyy-MM-dd'T'HH:mm:ss.SSSZ
